"""Log, register, and serve the Document Analyst (Tasks 2.2 + 2.3).

Run:  uv run python deployment/deploy.py
"""

from __future__ import annotations

import os
import time

import mlflow
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.serving import (
    EndpointCoreConfigInput,
    EndpointStateReady,
    ServedEntityInput,
)

from config import get_settings

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MODEL_NAME = os.environ.get("MODEL_NAME", "document_analyst")
UC_CATALOG = os.environ.get("UC_CATALOG", "main")
UC_SCHEMA = os.environ.get("UC_SCHEMA", "default")
SERVING_ENDPOINT_NAME = os.environ.get("SERVING_ENDPOINT_NAME", f"{MODEL_NAME}-endpoint")
SECRET_SCOPE = os.environ.get("SECRET_SCOPE", "cs4603-deploy")

PIP_REQUIREMENTS = [
    # Fully pinned — every transitive dependency, not just the 11 direct
    # ones — generated by `uv pip freeze` from a clean venv containing only
    # these direct deps. Three rounds of earlier attempts each failed the
    # container build differently:
    #   1. Fully unpinned: the resolver backtracked through hundreds of
    #      ancient `regex` releases (a transitive dep of `tiktoken` via
    #      `langchain-openai`), which can't build under the container's
    #      Python 3.13 (missing unicodedata_db.h).
    #   2. Only the 11 direct deps pinned: still left dozens of transitive
    #      deps unconstrained, and pip aborted with
    #      "resolution-too-deep — dependency graph is too complex".
    #   3. Fully pinned at 17.0.10: `databricks-connect==17.0.10` isn't on
    #      this workspace's serving-container package mirror (it tops out
    #      at 16.1.7) — "Could not find a version that satisfies...".
    # A fully frozen list makes pip do zero solving — it just installs the
    # exact versions listed, identical to what already works locally.
    #
    # `databricks-connect` deserves its own note: `databricks-langchain`
    # unconditionally requires `unitycatalog-langchain[databricks]`, which
    # unconditionally requires `databricks-connect<17.1,>=15.1.0` (for
    # Spark-Connect-backed UC function-calling tools this agent never
    # uses — we only use `databricks_langchain.DatabricksVectorSearch`).
    # Every version of `databricks-connect` in that range which is actually
    # present on this workspace's container mirror (<=16.1.7) pins
    # `numpy<2`, but `langchain-community>=0.4` (itself pulled in
    # unconditionally by `unitycatalog-langchain>=0.3.0`) requires
    # `numpy>=2.1` — a genuine, unresolvable version deadlock between two
    # of `databricks-langchain`'s own transitive dependencies, not
    # something a different pin choice can fix. Downgrading the whole
    # stack to avoid it (verified locally) lands on a `langchain-core` too
    # old for `langchain-mcp-adapters`, breaking MCP tool loading — worse.
    #
    # Fix: `deployment/stub_wheels/` ships a hand-built, dependency-free
    # `databricks-connect==17.0.10` wheel (see its docstring/METADATA) that
    # satisfies unitycatalog's version constraint without requiring numpy
    # at all. `--find-links` below points pip at it; because the real
    # 17.0.10 isn't on the mirror, this local stub is the only candidate
    # pip finds for that exact pin, so it's used deterministically. This
    # is safe because nothing in our actual import/runtime path touches
    # Spark Connect: `unitycatalog/ai/core/databricks.py` only imports
    # `databricks.connect.session` lazily inside `initialize_spark_session()`,
    # which we never call — verified by running the full graph
    # end-to-end (retrieval + MCP tool call) with this stub in place.
    "--find-links=/model/code/stub_wheels",
    "aiohappyeyeballs==2.7.1",
    "aiohttp==3.14.1",
    "aiohttp-retry==2.9.1",
    "aiosignal==1.4.0",
    "alembic==1.18.5",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.14.2",
    "attrs==26.1.0",
    "blinker==1.9.0",
    "cachetools==7.1.4",
    "certifi==2026.6.17",
    "cffi==2.1.0",
    "charset-normalizer==3.4.9",
    "click==8.4.2",
    "cloudpickle==3.1.2",
    "contourpy==1.3.3",
    "cryptography==48.0.1",
    "cycler==0.12.1",
    "databricks-ai-bridge==0.21.0",
    "databricks-ai-search==0.76",
    "databricks-connect==17.0.10",
    "databricks-langchain==0.20.0",
    "databricks-mcp==0.9.0",
    "databricks-openai==0.17.0",
    "databricks-sdk==0.120.0",
    "databricks-vectorsearch==0.75",
    "deprecation==2.1.0",
    "distro==1.9.0",
    "docker==7.2.0",
    "fastapi==0.139.0",
    "flask==3.1.3",
    "flask-cors==6.0.5",
    "fonttools==4.63.0",
    "frozenlist==1.8.0",
    "gitdb==4.0.12",
    "gitpython==3.1.51",
    "google-auth==2.56.0",
    "googleapis-common-protos==1.75.0",
    "graphene==3.4.3",
    "graphql-core==3.2.11",
    "graphql-relay==3.2.0",
    "griffelib==2.1.0",
    "grpcio==1.82.1",
    "grpcio-status==1.71.2",
    "gunicorn==26.0.0",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "httpx-sse==0.4.3",
    "huey==3.2.1",
    "idna==3.18",
    "importlib-metadata==9.0.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "jiter==0.16.0",
    "joblib==1.5.3",
    "jsonpatch==1.33",
    "jsonpointer==3.1.1",
    "jsonschema==4.26.0",
    "jsonschema-specifications==2025.9.1",
    "kiwisolver==1.5.0",
    "langchain==1.3.13",
    "langchain-classic==1.0.8",
    "langchain-community==0.4.2",
    "langchain-core==1.4.9",
    "langchain-mcp-adapters==0.3.0",
    "langchain-openai==1.3.5",
    "langchain-protocol==0.0.18",
    "langchain-text-splitters==1.1.2",
    "langgraph==1.2.9",
    "langgraph-checkpoint==4.1.1",
    "langgraph-prebuilt==1.1.0",
    "langgraph-sdk==0.4.2",
    "langsmith==0.10.2",
    "mako==1.3.12",
    "markupsafe==3.0.3",
    "matplotlib==3.11.0",
    "mcp==1.28.1",
    "mlflow==3.14.0",
    "mlflow-skinny==3.14.0",
    "mlflow-tracing==3.14.0",
    "multidict==6.7.1",
    "narwhals==2.24.0",
    "nest-asyncio==1.6.0",
    "numpy==2.5.1",
    "openai==2.45.0",
    "openai-agents==0.18.2",
    "opentelemetry-api==1.43.0",
    "opentelemetry-proto==1.43.0",
    "opentelemetry-sdk==1.43.0",
    "opentelemetry-semantic-conventions==0.64b0",
    "orjson==3.11.9",
    "ormsgpack==1.12.2",
    "packaging==26.2",
    "pandas==2.3.3",
    "pillow==12.3.0",
    "prettytable==3.18.0",
    "propcache==0.5.2",
    "protobuf==5.29.6",
    "py4j==0.10.9.9",
    "pyarrow==24.0.0",
    "pyasn1==0.6.4",
    "pyasn1-modules==0.4.2",
    "pycparser==3.0",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "pydantic-settings==2.14.2",
    "pyjwt==2.13.0",
    "pyparsing==3.3.2",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.2",
    "python-multipart==0.0.32",
    "pytz==2026.2",
    "pyyaml==6.0.3",
    "referencing==0.37.0",
    "regex==2026.7.10",
    "requests==2.34.2",
    "requests-toolbelt==1.0.0",
    "rpds-py==2026.6.3",
    "scikit-learn==1.9.0",
    "scipy==1.18.0",
    "setuptools==83.0.0",
    "six==1.17.0",
    "skops==0.14.0",
    "smmap==5.0.3",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.51",
    "sqlparse==0.5.5",
    "sse-starlette==3.4.5",
    "starlette==1.3.1",
    "tabulate==0.10.0",
    "tenacity==9.1.4",
    "threadpoolctl==3.6.0",
    "tiktoken==0.13.0",
    "tqdm==4.68.4",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.2",
    "tzdata==2026.3",
    "unitycatalog-ai==0.3.2",
    "unitycatalog-client==0.4.0",
    "unitycatalog-langchain==0.3.0",
    "unitycatalog-openai==0.2.0",
    "urllib3==2.7.0",
    "uuid-utils==0.17.0",
    "uvicorn==0.51.0",
    "wcwidth==0.8.2",
    "websockets==15.0.1",
    "werkzeug==3.1.8",
    "xxhash==3.8.1",
    "yarl==1.24.2",
    "zipp==4.1.0",
    "zstandard==0.25.0",
]


def log_and_register() -> tuple[str, str]:
    """Log the Document Analyst as an MLflow model and register it in Unity Catalog.

    Returns (uc_model_name, version) so create_or_update_endpoint() can point
    the serving endpoint at this exact registered version.
    """
    mlflow.set_registry_uri("databricks-uc")
    uc_model_name = f"{UC_CATALOG}.{UC_SCHEMA}.{MODEL_NAME}"

    with mlflow.start_run():
        model_info = mlflow.langchain.log_model(
            lc_model=os.path.join(_REPO_ROOT, "deployment", "agent_model.py"),
            name="agent",
            code_paths=[
                os.path.join(_REPO_ROOT, "agent"),
                os.path.join(_REPO_ROOT, "rag"),
                os.path.join(_REPO_ROOT, "tools"),
                os.path.join(_REPO_ROOT, "config.py"),
                os.path.join(_REPO_ROOT, "deployment", "stub_wheels"),
            ],
            pip_requirements=PIP_REQUIREMENTS,
            input_example={"messages": [{"role": "user", "content": "What was the revenue?"}]},
        )

    registered = mlflow.register_model(model_info.model_uri, uc_model_name)
    print(f"Registered model: {uc_model_name}, version {registered.version}")
    return uc_model_name, registered.version


def wait_for_ready(w: WorkspaceClient, name: str, settings: dict | None = None) -> str:
    """Poll `name` until its state is READY, then return its URL.

    Long-running network polls are expected to hit transient errors
    (a dropped connection, a sleep/wake cycle, a brief DNS blip) — those
    should not abort the whole wait. Only a genuinely broken endpoint
    (e.g. DEPLOYMENT_FAILED) should stop the loop early.
    """
    settings = settings or get_settings()
    status = None
    while True:
        try:
            status = w.serving_endpoints.get(name)
        except Exception as exc:  # noqa: BLE001 - transient network errors, keep polling
            print(f"Poll failed ({exc!r}), retrying in 30s...", flush=True)
            time.sleep(30)
            continue

        ready = status.state.ready if status.state else None
        print(f"Endpoint state: {ready}", flush=True)
        if ready == EndpointStateReady.READY:
            break
        time.sleep(30)

    url = status.endpoint_url or f"{settings['host']}/serving-endpoints/{name}/invocations"
    print(f"Endpoint URL: {url}", flush=True)
    return url


def create_or_update_endpoint(uc_name: str, version: str) -> str:
    """Create (or update) a Model Serving endpoint pointed at uc_name@version.

    Waits for the endpoint to reach READY and returns its URL.
    """
    settings = get_settings()
    w = WorkspaceClient()

    environment_vars = {
        # Secrets — never plaintext.
        "DATABRICKS_HOST": f"{{{{secrets/{SECRET_SCOPE}/DATABRICKS_HOST}}}}",
        "DATABRICKS_TOKEN": f"{{{{secrets/{SECRET_SCOPE}/DATABRICKS_TOKEN}}}}",
        "DATABRICKS_MODEL": f"{{{{secrets/{SECRET_SCOPE}/DATABRICKS_MODEL}}}}",
        # Not secrets — the retriever needs these to reach the index.
        "VECTOR_SEARCH_ENDPOINT": settings["vs_endpoint"],
        "VECTOR_SEARCH_INDEX": settings["vs_index"],
        "EMBEDDINGS_ENDPOINT": settings["embeddings"],
    }
    # Bonus C — point the agent at the standalone MCP Databricks App instead
    # of spawning the bundled stdio subprocess (agent/graph.py's
    # load_mcp_tools() falls back to stdio when this is unset). The App's
    # ingress requires an OAuth token, not DATABRICKS_TOKEN (a PAT) — see
    # agent/graph.py::_mint_mcp_oauth_token() — so a service-principal
    # client id/secret (granted CAN_USE on the app) must ride along too.
    mcp_server_url = os.environ.get("MCP_SERVER_URL")
    if mcp_server_url:
        environment_vars["MCP_SERVER_URL"] = mcp_server_url
        environment_vars["MCP_OAUTH_CLIENT_ID"] = f"{{{{secrets/{SECRET_SCOPE}/MCP_OAUTH_CLIENT_ID}}}}"
        environment_vars["MCP_OAUTH_CLIENT_SECRET"] = (
            f"{{{{secrets/{SECRET_SCOPE}/MCP_OAUTH_CLIENT_SECRET}}}}"
        )

    served_entities = [
        ServedEntityInput(
            entity_name=uc_name,
            entity_version=version,
            workload_size="Small",
            scale_to_zero_enabled=True,
            environment_vars=environment_vars,
        )
    ]

    existing_names = [e.name for e in w.serving_endpoints.list()]
    if SERVING_ENDPOINT_NAME not in existing_names:
        w.serving_endpoints.create(
            name=SERVING_ENDPOINT_NAME,
            config=EndpointCoreConfigInput(
                name=SERVING_ENDPOINT_NAME, served_entities=served_entities
            ),
        )
    else:
        w.serving_endpoints.update_config(
            name=SERVING_ENDPOINT_NAME,
            served_entities=served_entities,
        )

    return wait_for_ready(w, SERVING_ENDPOINT_NAME, settings)


if __name__ == "__main__":
    name, ver = log_and_register()
    create_or_update_endpoint(name, ver)
